### ISSUE TITLE
Create final Dense Layer

### ISSUE THREAD

**Issue by alexander34ro** [alexander34ro/AML-Replicating-Novel-Deep-Learning-with-CNN-and-Bi-Directional-LSTM-for-Improved-Index-Prediction#5]
<img width="341" alt="Screen Shot 2020-11-12 at 18 30 39" src="https://user-images.githubusercontent.com/16760229/98967448-2c238b80-2515-11eb-8caa-deec94899413.png">

**Comment by ariansajina** [comment]
Unclear from the paper: how do they predict prices for the _next 7 days_? Or do they predict the price for _7 days from now_?
Let's discuss this at a later point.
