### ISSUE TITLE
Complete report sections

### ISSUE THREAD

**Issue by alexander34ro** [alexander34ro/AML-Replicating-Novel-Deep-Learning-with-CNN-and-Bi-Directional-LSTM-for-Improved-Index-Prediction#7]
- Introduction
- Methods
- - Conv
- - Pooling
- - LSTM
- - Bi-directional
- - Dense
- Experiments
- - Dataset
- - Results
- Discussion
- - Comparison
- - Limitations
- Conclusions
- References

**Comment by ariansajina** [comment]
Good job with the references!

**Comment by alexander34ro** [comment]
I also completed the Dataset subsection. We are currently sitting at about 350/2000 words.

<img width="599" alt="Screen Shot 2020-11-16 at 18 06 49" src="https://user-images.githubusercontent.com/16760229/99277568-9ea6ab00-2836-11eb-932b-444c19d7996a.png">
