### ISSUE TITLE
Create 3 Pipelines out of 1

### ISSUE THREAD

**Issue by Akons97** [alexander34ro/AML-Replicating-Novel-Deep-Learning-with-CNN-and-Bi-Directional-LSTM-for-Improved-Index-Prediction#8]

**Comment by alexander34ro** [comment]
We need to: 
* create 3 pipelines, 
* concatenate the outputs, 
* combine them with a final Dense layer.

**Comment by amir-souri** [comment]
It is enough to code only one pipeline due to time restrictions.
We can explain how to do the 3 pipelines in the report.
